### ISSUE TITLE
Tell me your first story

### ISSUE THREAD

**Issue by Jacobvu84** [khanhtran86/flightbooking-automation#2]
@khanhtran86 
Pls Tell me your first story.

**Comment by khanhtran86** [comment]
As a user I want to search a flight from a specific location of Vietnam to another local destination, so that I may create a booking for my journey

**Comment by Jacobvu84** [comment]
Base on this template and write yours
I mean, you should try to write your story in the java code base on coding style that is like in the template [story](https://github.com/khanhtran86/flightbooking-automation/tree/master/src/test/java/com/learnauto/ticketbooking/features/search)

**Comment by Jacobvu84** [comment]
@khanhtran86 Base on your story we should have a java in coding style is like this
```
Search.a(flight).from(departure).to(destination)
```

**Comment by Jacobvu84** [comment]
Should create new java file with name `WhenTrallverBookingATicketStory.java` and keep `OpenTheApplication.java`


Delete all others files

**Comment by khanhtran86** [comment]
Completed create new file name with more code
